version: '3'
services:
    pagila-client:
        container_name: pagila-client
        image: node:20.16.0
        hostname: pagila-client
        ports:
            - 4200:4200
        networks:
            - pagila-network
        working_dir: /home/node/app
        volumes:
            - './:/home/node/app'
        entrypoint: ['/bin/sh', '-c']
        command:
            - |
                npm install
                npm start -- --host=0.0.0.0
networks:
    pagila-network:
        name: pagila-network
        external: true
