server {
    listen 80;

    location / {
        include /etc/nginx/mime.types;
        root /usr/share/nginx/html;
        # this redirects everything to index.html
        try_files $uri $uri/ /index.html =404;
    }
}
